# Generated by Django 5.2.17 on 2026-09-18 17:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=175, unique=True, verbose_name='название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='именование')),
            ],
            options={
                'verbose_name': 'Параметр',
                'verbose_name_plural': 'Параметры',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('patronymic', models.CharField(blank=True, max_length=255, null=True, verbose_name='отчество')),
                ('registration_token', models.CharField(blank=True, max_length=20, null=True, verbose_name='токен регистрации')),
                ('is_shop', models.BooleanField(default=False, verbose_name='магазин')),
                ('is_confirm', models.BooleanField(blank=True, default=False, null=True, verbose_name='подтвержденный')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('is_staff', models.BooleanField(default=False, verbose_name='работник')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='администратор')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=70, verbose_name='номер телефона')),
                ('settlement', models.CharField(max_length=40, verbose_name='поселение')),
                ('street', models.CharField(max_length=70, verbose_name='улица')),
                ('house', models.CharField(max_length=10, verbose_name='дом')),
                ('structure', models.CharField(blank=True, max_length=10, null=True, verbose_name='строение')),
                ('building', models.CharField(blank=True, max_length=10, null=True, verbose_name='корпус')),
                ('flat', models.CharField(blank=True, max_length=10, null=True, verbose_name='квартира')),
                ('comment', models.CharField(blank=True, max_length=90, null=True, verbose_name='комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано')),
                ('status', models.CharField(choices=[('NOT_CREATED', 'не создан'), ('PROCESSING', 'в обработке'), ('GETTING_READY', 'собирается'), ('ON_THE_WAY', 'доставляется'), ('DELIVERED', 'доставлен'), ('RETURNED', 'возвращен'), ('CANCELED', 'отменен'), ('ERROR', 'ошибка')], default='NOT_CREATED', max_length=15, verbose_name='статус')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.contact', verbose_name='контакты')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['id', 'created_at', 'status'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=175, verbose_name='название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['id', 'name', 'category'],
            },
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='not_specified', max_length=255, verbose_name='модель')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='стоимость')),
                ('price_rrc', models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='РРЦ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.product', verbose_name='товар')),
            ],
            options={
                'verbose_name': 'Информация о товаре',
                'verbose_name_plural': 'Информация о товарах',
                'ordering': ['id', 'name', 'quantity', 'price', 'price_rrc', 'shop', 'product'],
            },
        ),
        migrations.CreateModel(
            name='ProductParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=105, verbose_name='значение')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.parameter', verbose_name='параметр')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productinfo', verbose_name='информация о товаре')),
            ],
            options={
                'verbose_name': 'Значение параметра',
                'verbose_name_plural': 'Значения параметров',
                'ordering': ['id', 'parameter', 'value'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='наименование')),
                ('url', models.URLField(blank=True, null=True, unique=True, verbose_name='url')),
                ('status', models.CharField(choices=[('ACCEPT_ORDERS', 'принимаю заказы'), ('NOT_ACCEPT_ORDERS', 'не принимаю заказы')], default='ACCEPT_ORDERS', max_length=20, verbose_name='статус')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shop', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазины',
                'ordering': ['id', 'name'],
            },
        ),
        migrations.AddField(
            model_name='productinfo',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shop', verbose_name='магазин'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.order', verbose_name='заказ')),
                ('product_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.productinfo', verbose_name='информация о товаре')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.shop', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
                'ordering': ['id', 'product_info', 'shop', 'quantity'],
            },
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_category', to='backend.category', verbose_name='категория')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_category', to='backend.shop', verbose_name='магазин')),
            ],
            options={
                'verbose_name': 'Связь Магазин-Категория',
                'verbose_name_plural': 'Связи Магазины-Категории',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='category',
            name='shops',
            field=models.ManyToManyField(through='backend.ShopCategory', to='backend.shop', verbose_name='магазины'),
        ),
    ]
